name: Pandocテスト

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://pandoc/core:latest
        with:
          args: "/github/workspace/Pandoc.md -f markdown -t html -s -o /github/workspace/Pandoc.html"
